### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/skill-ovos-weather#26]
some planned TODOS:
- [ ] make skill weather provider agnostic
   - [ ] deprecate direct usage of ovosapiservice, move to ovos-backend-client 
- [ ] move to https://open-meteo.com for a free default provider
   - [ ] needs companion PR in ovos-backend-client / ovos-personal-backend
- [ ] adopt temporalis package, move all weather providers there - https://github.com/OpenJarbas/temporalis
